
INSERT INTO `countries` ( `name`, `code`, `dial_code`, `currency_name`, `currency_symbol`, `currency_code`, `created_at`, `updated_at`) VALUES
('Afghanistan', 'AF', '+93', 'Afghan afghani', '؋', 'AFN', NULL, NULL),
('Albania', 'AL', '+355', 'Albanian lek', 'L', 'ALL', NULL, NULL),
('Algeria', 'DZ', '+213', 'Algerian dinar', 'د.ج', 'DZD', NULL, NULL),
('Andorra', 'AD', '+376', 'Euro', '€', 'EUR', NULL, NULL),
('Angola', 'AO', '+244', 'Angolan kwanza', 'Kz', 'AOA', NULL, NULL),
('Anguilla', 'AI', '+1264', 'East Caribbean dolla', '$', 'XCD', NULL, NULL),
('Antigua and Barbuda', 'AG', '+1268', 'East Caribbean dolla', '$', 'XCD', NULL, NULL),
('Argentina', 'AR', '+54', 'Argentine peso', '$', 'ARS', NULL, NULL),
('Aruba', 'AW', '+297', 'Aruban florin', 'ƒ', 'AWG', NULL, NULL),
('Australia', 'AU', '+61', 'Australian dollar', '$', 'AUD', NULL, NULL),
('Austria', 'AT', '+43', 'Euro', '€', 'EUR', NULL, NULL),
('Bahrain', 'BH', '+973', 'Bahraini dinar', '.د.ب', 'BHD', NULL, NULL),
('Bangladesh', 'BD', '+880', 'Bangladeshi taka', '৳', 'BDT', NULL, NULL),
('Barbados', 'BB', '+1246', 'Barbadian dollar', '$', 'BBD', NULL, NULL),
('Belarus', 'BY', '+375', 'Belarusian ruble', 'Br', 'BYR', NULL, NULL),
('Belgium', 'BE', '+32', 'Euro', '€', 'EUR', NULL, NULL),
('Belize', 'BZ', '+501', 'Belize dollar', '$', 'BZD', NULL, NULL),
('Benin', 'BJ', '+229', 'West African CFA fra', 'Fr', 'XOF', NULL, NULL),
('Bermuda', 'BM', '+1441', 'Bermudian dollar', '$', 'BMD', NULL, NULL),
('Bhutan', 'BT', '+975', 'Bhutanese ngultrum', 'Nu.', 'BTN', NULL, NULL),
('Botswana', 'BW', '+267', 'Botswana pula', 'P', 'BWP', NULL, NULL),
('Brazil', 'BR', '+55', 'Brazilian real', 'R$', 'BRL', NULL, NULL),
('Bulgaria', 'BG', '+359', 'Bulgarian lev', 'лв', 'BGN', NULL, NULL),
('Burkina Faso', 'BF', '+226', 'West African CFA fra', 'Fr', 'XOF', NULL, NULL),
('Burundi', 'BI', '+257', 'Burundian franc', 'Fr', 'BIF', NULL, NULL),
('Cambodia', 'KH', '+855', 'Cambodian riel', '៛', 'KHR', NULL, NULL),
('Cameroon', 'CM', '+237', 'Central African CFA ', 'Fr', 'XAF', NULL, NULL),
('Canada', 'CA', '+1', 'Canadian dollar', '$', 'CAD', NULL, NULL),
('Cape Verde', 'CV', '+238', 'Cape Verdean escudo', '$', 'CVE', NULL, NULL),
('Cayman Islands', 'KY', '+ 345', 'Cayman Islands dolla', '$', 'KYD', NULL, NULL),
('Chad', 'TD', '+235', 'Central African CFA ', 'Fr', 'XAF', NULL, NULL),
('Chile', 'CL', '+56', 'Chilean peso', '$', 'CLP', NULL, NULL),
('China', 'CN', '+86', 'Chinese yuan', '¥', 'CNY', NULL, NULL),
('Colombia', 'CO', '+57', 'Colombian peso', '$', 'COP', NULL, NULL),
('Comoros', 'KM', '+269', 'Comorian franc', 'Fr', 'KMF', NULL, NULL),
('Cook Islands', 'CK', '+682', 'New Zealand dollar', '$', 'NZD', NULL, NULL),
('Costa Rica', 'CR', '+506', 'Costa Rican colón', '₡', 'CRC', NULL, NULL),
('Cote d\'Ivoire', 'CI', '+225', 'West African CFA fra', 'Fr', 'XOF', NULL, NULL),
('Croatia', 'HR', '+385', 'Croatian kuna', 'kn', 'HRK', NULL, NULL),
('Cuba', 'CU', '+53', 'Cuban convertible pe', '$', 'CUC', NULL, NULL),
('Cyprus', 'CY', '+357', 'Euro', '€', 'EUR', NULL, NULL),
('Czech Republic', 'CZ', '+420', 'Czech koruna', 'Kč', 'CZK', NULL, NULL),
('Denmark', 'DK', '+45', 'Danish krone', 'kr', 'DKK', NULL, NULL),
('Djibouti', 'DJ', '+253', 'Djiboutian franc', 'Fr', 'DJF', NULL, NULL),
('Dominica', 'DM', '+1767', 'East Caribbean dolla', '$', 'XCD', NULL, NULL),
('Dominican Republic', 'DO', '+1849', 'Dominican peso', '$', 'DOP', NULL, NULL),
('Ecuador', 'EC', '+593', 'United States dollar', '$', 'USD', NULL, NULL),
('Egypt', 'EG', '+20', 'Egyptian pound', '£', 'EGP', NULL, NULL),
('El Salvador', 'SV', '+503', 'United States dollar', '$', 'USD', NULL, NULL),
('Equatorial Guinea', 'GQ', '+240', 'Central African CFA ', 'Fr', 'XAF', NULL, NULL),
('Eritrea', 'ER', '+291', 'Eritrean nakfa', 'Nfk', 'ERN', NULL, NULL),
('Estonia', 'EE', '+372', 'Euro', '€', 'EUR', NULL, NULL),
('Ethiopia', 'ET', '+251', 'Ethiopian birr', 'Br', 'ETB', NULL, NULL),
('Faroe Islands', 'FO', '+298', 'Danish krone', 'kr', 'DKK', NULL, NULL),
('Fiji', 'FJ', '+679', 'Fijian dollar', '$', 'FJD', NULL, NULL),
('Finland', 'FI', '+358', 'Euro', '€', 'EUR', NULL, NULL),
('France', 'FR', '+33', 'Euro', '€', 'EUR', NULL, NULL),
('French Polynesia', 'PF', '+689', 'CFP franc', 'Fr', 'XPF', NULL, NULL),
('Gabon', 'GA', '+241', 'Central African CFA ', 'Fr', 'XAF', NULL, NULL),
('Georgia', 'GE', '+995', 'Georgian lari', 'ლ', 'GEL', NULL, NULL),
('Germany', 'DE', '+49', 'Euro', '€', 'EUR', NULL, NULL),
('Ghana', 'GH', '+233', 'Ghana cedi', '₵', 'GHS', NULL, NULL),
('Gibraltar', 'GI', '+350', 'Gibraltar pound', '£', 'GIP', NULL, NULL),
('Greece', 'GR', '+30', 'Euro', '€', 'EUR', NULL, NULL),
('Grenada', 'GD', '+1473', 'East Caribbean dolla', '$', 'XCD', NULL, NULL),
('Guatemala', 'GT', '+502', 'Guatemalan quetzal', 'Q', 'GTQ', NULL, NULL),
('Guernsey', 'GG', '+44', 'British pound', '£', 'GBP', NULL, NULL),
('Guinea', 'GN', '+224', 'Guinean franc', 'Fr', 'GNF', NULL, NULL),
('Guinea-Bissau', 'GW', '+245', 'West African CFA fra', 'Fr', 'XOF', NULL, NULL),
('Guyana', 'GY', '+595', 'Guyanese dollar', '$', 'GYD', NULL, NULL),
('Haiti', 'HT', '+509', 'Haitian gourde', 'G', 'HTG', NULL, NULL),
('Honduras', 'HN', '+504', 'Honduran lempira', 'L', 'HNL', NULL, NULL),
('Hong Kong', 'HK', '+852', 'Hong Kong dollar', '$', 'HKD', NULL, NULL),
('Hungary', 'HU', '+36', 'Hungarian forint', 'Ft', 'HUF', NULL, NULL),
('Iceland', 'IS', '+354', 'Icelandic króna', 'kr', 'ISK', NULL, NULL),
('India', 'IN', '+91', 'Indian rupee', '₹', 'INR', NULL, NULL),
('Indonesia', 'ID', '+62', 'Indonesian rupiah', 'Rp', 'IDR', NULL, NULL),
('Iraq', 'IQ', '+964', 'Iraqi dinar', 'ع.د', 'IQD', NULL, NULL),
('Ireland', 'IE', '+353', 'Euro', '€', 'EUR', NULL, NULL),
('Isle of Man', 'IM', '+44', 'British pound', '£', 'GBP', NULL, NULL),
('Israel', 'IL', '+972', 'Israeli new shekel', '₪', 'ILS', NULL, NULL),
('Italy', 'IT', '+39', 'Euro', '€', 'EUR', NULL, NULL),
('Jamaica', 'JM', '+1876', 'Jamaican dollar', '$', 'JMD', NULL, NULL),
('Japan', 'JP', '+81', 'Japanese yen', '¥', 'JPY', NULL, NULL),
('Jersey', 'JE', '+44', 'British pound', '£', 'GBP', NULL, NULL),
('Jordan', 'JO', '+962', 'Jordanian dinar', 'د.ا', 'JOD', NULL, NULL),
('Kenya', 'KE', '+254', 'Kenyan shilling', 'Sh', 'KES', NULL, NULL),
('Kiribati', 'KI', '+686', 'Australian dollar', '$', 'AUD', NULL, NULL),
('Kuwait', 'KW', '+965', 'Kuwaiti dinar', 'د.ك', 'KWD', NULL, NULL),
('Kyrgyzstan', 'KG', '+996', 'Kyrgyzstani som', 'лв', 'KGS', NULL, NULL),
('Laos', 'LA', '+856', 'Lao kip', '₭', 'LAK', NULL, NULL),
('Latvia', 'LV', '+371', 'Euro', '€', 'EUR', NULL, NULL),
('Lebanon', 'LB', '+961', 'Lebanese pound', 'ل.ل', 'LBP', NULL, NULL),
('Lesotho', 'LS', '+266', 'Lesotho loti', 'L', 'LSL', NULL, NULL),
('Liberia', 'LR', '+231', 'Liberian dollar', '$', 'LRD', NULL, NULL),
('Liechtenstein', 'LI', '+423', 'Swiss franc', 'Fr', 'CHF', NULL, NULL),
('Lithuania', 'LT', '+370', 'Euro', '€', 'EUR', NULL, NULL),
('Luxembourg', 'LU', '+352', 'Euro', '€', 'EUR', NULL, NULL),
('Madagascar', 'MG', '+261', 'Malagasy ariary', 'Ar', 'MGA', NULL, NULL),
('Malawi', 'MW', '+265', 'Malawian kwacha', 'MK', 'MWK', NULL, NULL),
('Malaysia', 'MY', '+60', 'Malaysian ringgit', 'RM', 'MYR', NULL, NULL),
('Maldives', 'MV', '+960', 'Maldivian rufiyaa', '.ރ', 'MVR', NULL, NULL),
('Mali', 'ML', '+223', 'West African CFA fra', 'Fr', 'XOF', NULL, NULL),
('Malta', 'MT', '+356', 'Euro', '€', 'EUR', NULL, NULL),
('Marshall Islands', 'MH', '+692', 'United States dollar', '$', 'USD', NULL, NULL),
('Mauritania', 'MR', '+222', 'Mauritanian ouguiya', 'UM', 'MRO', NULL, NULL),
('Mauritius', 'MU', '+230', 'Mauritian rupee', '₨', 'MUR', NULL, NULL),
('Mexico', 'MX', '+52', 'Mexican peso', '$', 'MXN', NULL, NULL),
('Moldova', 'MD', '+373', 'Moldovan leu', 'L', 'MDL', NULL, NULL),
('Monaco', 'MC', '+377', 'Euro', '€', 'EUR', NULL, NULL),
('Mongolia', 'MN', '+976', 'Mongolian tögrög', '₮', 'MNT', NULL, NULL),
('Montenegro', 'ME', '+382', 'Euro', '€', 'EUR', NULL, NULL),
('Montserrat', 'MS', '+1664', 'East Caribbean dolla', '$', 'XCD', NULL, NULL),
('Morocco', 'MA', '+212', 'Moroccan dirham', 'د.م.', 'MAD', NULL, NULL),
('Mozambique', 'MZ', '+258', 'Mozambican metical', 'MT', 'MZN', NULL, NULL),
('Myanmar', 'MM', '+95', 'Burmese kyat', 'Ks', 'MMK', NULL, NULL),
('Namibia', 'NA', '+264', 'Namibian dollar', '$', 'NAD', NULL, NULL),
('Nauru', 'NR', '+674', 'Australian dollar', '$', 'AUD', NULL, NULL),
('Nepal', 'NP', '+977', 'Nepalese rupee', '₨', 'NPR', NULL, NULL),
('Netherlands', 'NL', '+31', 'Euro', '€', 'EUR', NULL, NULL),
('New Caledonia', 'NC', '+687', 'CFP franc', 'Fr', 'XPF', NULL, NULL),
('New Zealand', 'NZ', '+64', 'New Zealand dollar', '$', 'NZD', NULL, NULL),
('Nicaragua', 'NI', '+505', 'Nicaraguan córdoba', 'C$', 'NIO', NULL, NULL),
('Niger', 'NE', '+227', 'West African CFA fra', 'Fr', 'XOF', NULL, NULL),
('Nigeria', 'NG', '+234', 'Nigerian naira', '₦', 'NGN', NULL, NULL),
('Niue', 'NU', '+683', 'New Zealand dollar', '$', 'NZD', NULL, NULL),
('Norway', 'NO', '+47', 'Norwegian krone', 'kr', 'NOK', NULL, NULL),
('Oman', 'OM', '+968', 'Omani rial', 'ر.ع.', 'OMR', NULL, NULL),
('Pakistan', 'PK', '+92', 'Pakistani rupee', '₨', 'PKR', NULL, NULL),
('Panama', 'PA', '+507', 'Panamanian balboa', 'B/.', 'PAB', NULL, NULL),
('Papua New Guinea', 'PG', '+675', 'Papua New Guinean ki', 'K', 'PGK', NULL, NULL),
('Paraguay', 'PY', '+595', 'Paraguayan guaraní', '₲', 'PYG', NULL, NULL),
('Peru', 'PE', '+51', 'Peruvian nuevo sol', 'S/.', 'PEN', NULL, NULL),
('Philippines', 'PH', '+63', 'Philippine peso', '₱', 'PHP', NULL, NULL),
('Poland', 'PL', '+48', 'Polish z?oty', 'zł', 'PLN', NULL, NULL),
('Portugal', 'PT', '+351', 'Euro', '€', 'EUR', NULL, NULL),
('Qatar', 'QA', '+974', 'Qatari riyal', 'ر.ق', 'QAR', NULL, NULL),
('Romania', 'RO', '+40', 'Romanian leu', 'lei', 'RON', NULL, NULL),
('Rwanda', 'RW', '+250', 'Rwandan franc', 'Fr', 'RWF', NULL, NULL),
('Saint Lucia', 'LC', '+1758', 'East Caribbean dolla', '$', 'XCD', NULL, NULL),
('Samoa', 'WS', '+685', 'Samoan t?l?', 'T', 'WST', NULL, NULL),
('San Marino', 'SM', '+378', 'Euro', '€', 'EUR', NULL, NULL),
('Saudi Arabia', 'SA', '+966', 'Saudi riyal', 'ر.س', 'SAR', NULL, NULL),
('Senegal', 'SN', '+221', 'West African CFA fra', 'Fr', 'XOF', NULL, NULL),
('Serbia', 'RS', '+381', 'Serbian dinar', 'din', 'RSD', NULL, NULL),
('Seychelles', 'SC', '+248', 'Seychellois rupee', '₨', 'SCR', NULL, NULL),
('Sierra Leone', 'SL', '+232', 'Sierra Leonean leone', 'Le', 'SLL', NULL, NULL),
('Singapore', 'SG', '+65', 'Brunei dollar', '$', 'BND', NULL, NULL),
('Slovakia', 'SK', '+421', 'Euro', '€', 'EUR', NULL, NULL),
('Slovenia', 'SI', '+386', 'Euro', '€', 'EUR', NULL, NULL),
('Solomon Islands', 'SB', '+677', 'Solomon Islands doll', '$', 'SBD', NULL, NULL),
('Somalia', 'SO', '+252', 'Somali shilling', 'Sh', 'SOS', NULL, NULL),
('South Africa', 'ZA', '+27', 'South African rand', 'R', 'ZAR', NULL, NULL),
('Spain', 'ES', '+34', 'Euro', '€', 'EUR', NULL, NULL),
('Sri Lanka', 'LK', '+94', 'Sri Lankan rupee', 'රු', 'LKR', NULL, NULL),
('Sudan', 'SD', '+249', 'Sudanese pound', 'ج.س.', 'SDG', NULL, NULL),
('Suriname', 'SR', '+597', 'Surinamese dollar', '$', 'SRD', NULL, NULL),
('Swaziland', 'SZ', '+268', 'Swazi lilangeni', 'L', 'SZL', NULL, NULL),
('Sweden', 'SE', '+46', 'Swedish krona', 'kr', 'SEK', NULL, NULL),
('Switzerland', 'CH', '+41', 'Swiss franc', 'Fr', 'CHF', NULL, NULL),
('Taiwan', 'TW', '+886', 'New Taiwan dollar', '$', 'TWD', NULL, NULL),
('Tajikistan', 'TJ', '+992', 'Tajikistani somoni', 'ЅМ', 'TJS', NULL, NULL),
('Thailand', 'TH', '+66', 'Thai baht', '฿', 'THB', NULL, NULL),
('Togo', 'TG', '+228', 'West African CFA fra', 'Fr', 'XOF', NULL, NULL),
('Tonga', 'TO', '+676', 'Tongan pa?anga', 'T$', 'TOP', NULL, NULL),
('Trinidad and Tobago', 'TT', '+1868', 'Trinidad and Tobago ', '$', 'TTD', NULL, NULL),
('Tunisia', 'TN', '+216', 'Tunisian dinar', 'د.ت', 'TND', NULL, NULL),
('Turkmenistan', 'TM', '+993', 'Turkmenistan manat', 'm', 'TMT', NULL, NULL),
('Tuvalu', 'TV', '+688', 'Australian dollar', '$', 'AUD', NULL, NULL),
('Uganda', 'UG', '+256', 'Ugandan shilling', 'Sh', 'UGX', NULL, NULL),
('Ukraine', 'UA', '+380', 'Ukrainian hryvnia', '₴', 'UAH', NULL, NULL),
('United Arab Emirates', 'AE', '+971', 'United Arab Emirates', 'د.إ', 'AED', NULL, NULL),
('United Kingdom', 'GB', '+44', 'British pound', '£', 'GBP', NULL, NULL),
('United States', 'US', '+1', 'United States dollar', '$', 'USD', NULL, NULL),
('Uruguay', 'UY', '+598', 'Uruguayan peso', '$', 'UYU', NULL, NULL),
('Vanuatu', 'VU', '+678', 'Vanuatu vatu', 'Vt', 'VUV', NULL, NULL),
('Vietnam', 'VN', '+84', 'Vietnamese ??ng', '₫', 'VND', NULL, NULL),
('Wallis and Futuna', 'WF', '+681', 'CFP franc', 'Fr', 'XPF', NULL, NULL),
('Yemen', 'YE', '+967', 'Yemeni rial', '﷼', 'YER', NULL, NULL),
('Zambia', 'ZM', '+260', 'Zambian kwacha', 'ZK', 'ZMW', NULL, NULL),
('Zimbabwe', 'ZW', '+263', 'Botswana pula', 'P', 'BWP', NULL, NULL);